drop table CLREG CASCADE;
drop table CLDEPT CASCADE;
drop table COMMUNE CASCADE;
drop table DEPARTEMENT CASCADE;
drop table REGION CASCADE;
drop table STATSCOMANNEE CASCADE;
drop table STATSCOMINTER CASCADE;
drop table STATS CASCADE;
