CREATE OR REPLACE VIEW populations_departements
AS
    SELECT T.IDSTAT, T.LABEL, D.CDEPT, SUM(S.VALEUR) as habitants FROM DEPARTEMENT D, COMMUNE C, STATSCOMANNEE S, STATS T 
    WHERE D.CDEPT = C.CDEPT 
    AND C.CCOM = S.IDCOM 
    AND T.IDSTAT LIKE '%POP%'
    AND S.IDSTAT = T.IDSTAT 
    GROUP BY(T.LABEL, D.CDEPT, T.IDSTAT) 
    ORDER BY habitants;