CREATE VIEW stats_departement
AS
    SELECT T.IDSTAT, D.NCC, SUM(S.VALEUR) as statValue FROM DEPARTEMENT D, COMMUNE C, STATSCOMANNEE S, STATS T 
    WHERE D.CDEPT = C.CDEPT 
    AND C.CCOM = S.IDCOM 
    AND S.IDSTAT = T.IDSTAT 
    GROUP BY(T.IDSTAT, D.NCC)
    UNION 
    SELECT T.IDSTAT, D.NCC, SUM(S.VALEUR) as statValue FROM DEPARTEMENT D, COMMUNE C, STATSCOMINTER S, STATS T 
    WHERE D.CDEPT = C.CDEPT 
    AND C.CCOM = S.IDCOM 
    AND S.IDSTAT = T.IDSTAT 
    GROUP BY(T.IDSTAT, D.NCC);