CREATE VIEW stat_region
AS
    SELECT T.IDSTAT, R.NCC, SUM(S.VALEUR) as statValue FROM REGION R, COMMUNE C, STATSCOMANNEE S, STATS T 
    WHERE R.CREG = C.CREG 
    AND C.CCOM = S.IDCOM 
    AND S.IDSTAT = T.IDSTAT 
    GROUP BY(T.IDSTAT, R.NCC)
    UNION 
    SELECT T.IDSTAT, R.NCC, SUM(S.VALEUR) as statValue FROM REGION R, COMMUNE C, STATSCOMINTER S, STATS T 
    WHERE R.CREG = C.CREG 
    AND C.CCOM = S.IDCOM 
    AND S.IDSTAT = T.IDSTAT 
    GROUP BY(T.IDSTAT, R.NCC);